services:
  - type: web
    name: onexp-siteshot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/.cache/puppeteer